name: Backend Tests

on:
  push:
    branches: [main, master, develop]
  pull_request:

jobs:
  test-all-microservices:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Jebed1ah15car10t
          MYSQL_DATABASE: smartpanda
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -pJebed1ah15car10t"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (Meni)
        run: npm ci
        working-directory: ./Meni

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -uroot -pJebed1ah15car10t --silent; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Load initial schema/data
        run: |
          mysql -h 127.0.0.1 -uroot -pJebed1ah15car10t smartpanda < dump.sql

      - name: Run Jest tests for Meni
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: Jebed1ah15car10t
          DB_NAME: smartpanda
        run: npm run test:ci
        working-directory: ./Meni

      # --- Odobrenje_Narocila tests ---
      - name: Install dependencies (Odobrenje_Narocila)
        run: npm ci
        working-directory: ./Odobrenje_Narocila

      - name: Run Odobrenje_Narocila tests
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: Jebed1ah15car10t
          DB_NAME: smartpanda
        run: npm run test:ci
        working-directory: ./Odobrenje_Narocila

      # --- Narocanje_jedi tests ---
      - name: Install dependencies (Narocanje_jedi)
        run: npm ci
        working-directory: ./Narocanje_jedi

      - name: Run Narocanje_jedi tests
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: Jebed1ah15car10t
          DB_NAME: smartpanda
          GRPC_HOST: localhost
          GRPC_PORT: 50051
        run: npm run test:ci
        working-directory: ./Narocanje_jedi
