# Backend CI for Meni/backend microservice
name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: Meni/backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('Meni/backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install dependencies
        run: |
          cd Meni/backend
          npm install

      - name: Upload backend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: |
            Meni/backend/
            Meni/backend/node_modules/

  test-backend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: Meni/backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('Meni/backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install dependencies
        run: |
          cd Meni/backend
          npm install

      - name: Fix Jest permissions
        run: chmod +x Meni/backend/node_modules/.bin/jest

      - name: Run tests with coverage
        run: |
          cd Meni/backend
          npm run test:ci

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: Meni/backend/coverage/
